#!/bin/bash
set -e

echo "=========================================="
echo "Solray iOS Build Automation (Steps 2-3)"
echo "=========================================="
echo ""

# Step 2: Add iOS platform
echo "Step 2: Adding iOS platform..."
echo "Running: npx cap add ios"
npx cap add ios

echo ""
echo "✅ iOS platform added"
echo ""
echo "Committing ios/ directory..."
git add ios
git commit -m "chore(ios): scaffold Capacitor iOS project"
git push

echo ""
echo "=========================================="
echo "Step 3: Syncing web build into iOS..."
echo "Running: npx cap sync ios"
npx cap sync ios

echo ""
echo "✅ Web build synced"
echo ""

echo "=========================================="
echo "AUTOMATED STEPS COMPLETE"
echo "=========================================="
echo ""
echo "🎯 NEXT: Manual Steps 4-7 (requires Xcode + iPhone)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 4: Add Microphone Permission to Info.plist"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Open the plist file:"
echo "  open ios/App/App/Info.plist"
echo ""
echo "In the XML editor, find the <dict> near the top, and add this"
echo "BEFORE the closing </dict>:"
echo ""
echo "  <key>NSMicrophoneUsageDescription</key>"
echo "  <string>Solray uses the microphone so you can speak with the Higher Self instead of typing.</string>"
echo ""
echo "Save (Cmd+S), then commit:"
echo "  git add ios/App/App/Info.plist"
echo "  git commit -m 'ios: declare microphone usage description'"
echo "  git push"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 5: Open in Xcode"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Run this to open Xcode with the iOS project:"
echo "  npx cap open ios"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 6: Configure Code Signing"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "In Xcode:"
echo "  1. Click 'App' project (left sidebar)"
echo "  2. Click 'App' target (middle pane)"
echo "  3. Click 'Signing & Capabilities' tab (top)"
echo "  4. Check ☑ 'Automatically manage signing'"
echo "  5. Team dropdown → select your Apple Developer team"
echo "  6. Bundle ID should be 'ai.solray.app' ✓"
echo ""
echo "Xcode will provision a development cert. If you get"
echo "'Failed to register bundle identifier', visit:"
echo "  https://developer.apple.com/account/resources/identifiers/list"
echo ""
echo "Click +, App IDs, App, register ai.solray.app, then retry."
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 7: First Test Build on Real Device"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "On your Mac:"
echo "  1. Plug iPhone into USB"
echo "  2. Trust the computer if prompted on phone"
echo "  3. iPhone: Settings → Privacy & Security → Developer Mode → ON"
echo ""
echo "In Xcode:"
echo "  1. Top toolbar: device picker → select your iPhone"
echo "  2. Press Cmd+R to build and run"
echo ""
echo "App will install and open. Test the mic:"
echo "  1. Log in with your Solray account"
echo "  2. Open Chat"
echo "  3. Tap the mic 🎤 icon"
echo "  4. Approve 'Allow Microphone' when prompted"
echo "  5. Speak something (should show 'Listening...')"
echo "  6. Tap mic again to stop"
echo "  7. Transcription should appear in the input box"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "TROUBLESHOOTING (Step 7)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Problem: Permission sheet never appeared"
echo "  → NSMicrophoneUsageDescription missing from Info.plist"
echo "  → Fix Step 4, re-run Cmd+R"
echo ""
echo "Problem: Permission sheet appeared but I tapped 'Don't Allow'"
echo "  → Settings → Solray → Microphone → Allow"
echo "  → Relaunch app"
echo ""
echo "Problem: Mic records but transcription never returns"
echo "  → Check Railway logs: [chat] /chat/transcribe"
echo "  → Backend may not handle m4a audio format yet"
echo ""
echo "Problem: Plugin missing / build fails"
echo "  → Run: npx cap sync ios"
echo "  → Then Cmd+R again"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 WHEN YOU'RE DONE:"
echo ""
echo "Once Step 7 mic test is complete, report back:"
echo "  ✅ 'Mic is working' → Ready for TestFlight"
echo "  ❌ 'Mic failed with [error]' → I'll diagnose"
echo ""
echo "Also: File Apple Reader App entitlement TODAY at:"
echo "  https://developer.apple.com/contact/request/reader-app-entitlement/"
echo ""
echo "Takes 2-4 weeks to process. Do this in parallel while testing."
echo ""
echo "=========================================="
